// <auto-generated />
namespace News_Article_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class uniqueness : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(uniqueness));
        
        string IMigrationMetadata.Id
        {
            get { return "202510300506231_uniqueness"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
